DIR_ROOT:=../..
DIR_SUB_LIST:=\



FILE_LIST_C +=\
mySort.c

FILE_LIST_CPP +=\

FILE_DYNAMIC_NAME +=\
sorts
FILE_STATIC_NAME +=\

all:make_current_folder
#all:mk_libdynamic 
include $(DIR_ROOT)/common.mk